### PR TITLE
Changes to restore Python 3.8 compatibility

### PR DESCRIPTION
**Pull request by andrewsoltan**
1. Revert to old-style typing importing to add Python 3.8 backwards (capitalisation of List and Dict)
2. Correct parentheses use around file opening command for python 3.8 compatibility

### CODE REVIEW

**Review by baixiac — COMMENTED** [review]
Hi, @andrewsoltan, Can you add py38 to this GH [workflow](https://github.com/CogStack/CogStack-ModelServe/blob/ea0da0146c278547aa521a7123df093ef5445e84/.github/workflows/main.yaml#L15C1-L15C42) and see if the CI works fine? Thanks.

**Comment by andrewsoltan** [comment]
Thanks - have added this to the workflow, I think just waiting on approval to be able to test out the CI

**Comment by baixiac** [comment]
Alright, please rebase the master branch onto your PR branch. It should fix the issue caused by the backward incompatibility of HF transformers, as shown in the earlier GH action run.

**Comment by andrewsoltan** [comment]
Great, thanks, I've just done that - over to you for approval :)

**Comment by baixiac** [comment]
To make the hashlib calls compatible to py38, can you remove all the occurences of `usedforsecurity=False` from `hashlib.sha1([TARGET], usedforsecurity=False).hexdigest()` in "app/processors/metrics_collector.py"?

**Review by baixiac — APPROVED** [review]
LGTM 👍

**Pull request merged**
