### PR TITLE
feat: Allow passing a tracking ID for API requests with side-effects

### PR DESCRIPTION
**Pull request by phoevos**
Some of the requests supported by the API have "persisted" side-effects like:
* logging a run on MLflow
* returning a file as the HTTP response

Given that other systems might need to track (e.g. monitor training progress on MLflow) or store these results (e.g. export responses to an object store), it's worth extending the relevant routes to accept an optional `tracking_id` query parameter, shifting the responsibility for generating and keeping track of IDs to the caller. If an ID is not provided, a UUID is generated and used in downstream tasks like before.

For 5 of the routes affected by this PR (i.e. `/train_supervised`, `/train_unsupervised`, `/train_unsupervised_with_hf_hub_dataset`, `/train_metacat`, and `/evaluate`), the tracking ID ends up being the name of the triggered MLflow run.

In the remaining cases, the tracking ID is used as part of the filename in the response's `Content-Disposition` header.

The serving tests are extended to check that the ID (if provided) is included in the response.

### CODE REVIEW

**Review by baixiac — COMMENTED** [review]
The change looks good. Given the user could now send in any arbitrary strings, can this also verify if `track_id` is a valid UUID and fail earlier if not?

**Comment by phoevos** [comment]
@baixiac I'm thinking about how we should handle this. I see that the UUIDs MLflow creates (e.g. see [here](https://github.com/mlflow/mlflow/blob/92a1664ddbd7ef59f8db45e988e41437d179c3b1/mlflow/store/tracking/file_store.py#L662)) are converted to their hex format when used as run IDs. But there's no reason not to support the standard format used in the Gateway as well, e.g. `"123e4567-e89b-12d3-a456-426614174000"`. In fact, MLflow's validation for user-provided ID strings is much more lenient, it doesn't really require them to be UUIDs (see [here](https://github.com/mlflow/mlflow/blob/92a1664ddbd7ef59f8db45e988e41437d179c3b1/mlflow/utils/validation.py#L374-L377)). WDYT? I agree we should have some sort of validation there, but should we actually enforce that the inputs are valid UUIDs (we can support both formats) or should we just check that they're alphanumeric strings between 1-256 characters like MLflow does?

**Comment by phoevos** [comment]
Great, I did it the MLflow way, allowing alphanumeric strings of length 1-256, PTAL!

**Review by baixiac — APPROVED** [review]
LGTM

**Pull request merged**
